name: Ionic Android Build (Debug)

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-ionic:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Get the code
      - uses: actions/checkout@v4

      # Enable KVM for emulator
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # Setup min version of Java required by Gradle v8
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # Let gradle action handle all cache reated to gradle operations
      - name: Gradle setup/cache
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: NodeJS v14 setup
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: "npm"

      - name: Instal dependencies
        run: npm ci

      - name: Print ionic info
        run: ionic info

      - name: Check Cordova Requirements
        run: ionic cordova requirements

      - name: Remove Android platform
        run: ionic cordova platform remove android

      - name: Add Android platform
        run: ionic cordova platform add android@13.0.0

      - name: Build Android
        run: ionic cordova build android --debug
